title: Stipendio Netto
description: >-
  Calcolo dello stipendio netto mensile a partire dal reddito annuo lordo (RAL), senza tracker, 100% open source!
twitter_username: alesanfra
github_username:  alesanfra
linkedin_username: alessiosanfratello

# Build settings
theme: minima
